#!/bin/sh
echo "good morning"
echo 'hello world'
echo 'hello'
echo "binod bro"
echo change
echo "hhhh"
ssh app@ip-http://3.86.207.251<<EOF
  cd ~/jenkins-nodejs-lab
  git pull
  npm install
  exit
EOF
